[package]
name = "rust-advent-template-populated"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rudvent-lib = { version = "0.1.0", path = "../../../rudvent-lib" }
tracing = "0.1.40"

