[package]
name = "rudvent"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
bounded-vec-deque = "0.1"
terminal-clipboard = "0.3"
array2d = "0.2"
